services:
  jupyterlab:
    build:
      context: .
      dockerfile: services/jupyterlab/Dockerfile
    image: braindock/jupyterlab:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./services/shared_module:/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}

  superset:
    image: apache/superset:latest
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=supersecret
    build: ./services/superset
    volumes:
      - ./services/superset:/app/superset_home
    depends_on:
      - clickhouse

  airbyte:
    image: airbyte/airbyte:oss
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - AIRBYTE_ROLE=dev
    depends_on:
      - clickhouse

  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./models:/mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - neo4j_data:/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9100:9000"   # 🟡 aqui a porta externa 9100 → interna 9000
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - minio_data:/data

  faiss:
    image: braindock/jupyterlab:latest
    container_name: faiss
    command: tail -f /dev/null
    volumes:
      - ./vectorstore:/faiss
    depends_on:
        - jupyterlab

  python-shell:
    image: braindock/jupyterlab:latest
    container_name: python-shell
    tty: true
    stdin_open: true
    command: bash
    healthcheck:
      test: ["CMD", "true"]
    volumes:
      - ./services/shared_module:/app
      - ./notebooks:/app/notebooks
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
      - USE_GPU=${USE_GPU}
    depends_on:
      - jupyterlab

  braindock-hub:
      image: braindock/jupyterlab:latest  # Reutiliza a imagem do python-shell
      container_name: braindock-hub
      command: streamlit run streamlit_app.py --server.port=8501 --server.enableXsrfProtection=false
      ports:
        - "8501:8501"
      volumes:
        - ./services/shared_module:/app/shared_module
        - ./services/brainhub:/app
      working_dir: /app
      environment:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
        - IMPORT_REPO=${IMPORT_REPO}
      depends_on:
        - jupyterlab

volumes:
  clickhouse_data:
  neo4j_data:
  minio_data:
